### ISSUE TITLE
Girder load issue with versions 4.19 or higher

### ISSUE THREAD

**Issue by imilos** [Kitware/Glance#433]
We have successfully deployed and used Glance in combination with Girder for almost 3 years. However, newer versions released after January 2022 seem to have a problem reading files from Girder. Upon clicking **Select** on any file stored on (https://data.kitware.com/api/v1), the wheel rotates indefinitely with an error:
```
[Vue warn]: Error in v-on handler: "TypeError: file.remoteOpts is undefined"

found in

---> <VBtn>
       <VToolbar>
         <GirderBox> at src/components/core/GirderBox/index.vue
           <VTabItem>
             <VTabsItems>
               <VTabs>
                 <VCard>... (1 recursive calls)
                   <VThemeProvider>
                     <VDialog>
                       <FileLoader> at src/components/core/FileLoader/index.vue
                         <VApp>
                           <DragAndDrop> at src/components/widgets/DragAndDrop/index.vue
                             <App> at src/components/core/App/index.vue
                               <Root> [vue.esm.js:629:15](webpack://paraview-glance/./node_modules/vue/dist/vue.esm.js?)
```
Any ideas for a workaround? With 4.18 and earlier versions, the file would normally load. Thanks in advance!

**Comment by floryst** [comment]
Hi, which version are you seeing this occur on?

**Comment by floryst** [comment]
Actually, I found the cause of the issue. The linked PR will fix this.
