### ISSUE TITLE
Proposal for reducing "noise" associated with GitHub unused features

### ISSUE THREAD

**Issue by jcfr** [Kitware/Glance#436]
I suggest to move forward with the following:

* Disabling unused `Discussing` tab
* Disabling unused `Projects` tab
* Hiding unused `Packages` section

If that seems reasonable, let me know and i will move forward with this proposal.

![image](https://user-images.githubusercontent.com/219043/168144012-10c7f5f5-a545-4af7-92fe-1d0c25156d23.png)

cc: @floryst

**Comment by floryst** [comment]
I support this proposal. We can definitely remove those features for now.

**Comment by jcfr** [comment]
Closing. The updates have been implemented.

![image](https://user-images.githubusercontent.com/219043/168161911-0b7c7c5d-d05d-4e82-a291-691bf6a414d4.png)
