### ISSUE TITLE
Fix link associated with GitHub project

### ISSUE THREAD

**Issue by jcfr** [Kitware/Glance#437]
Since the link are case-sensitive, the link should be updated from `https://kitware.github.io/glance` to `https://kitware.github.io/Glance`.

![image](https://user-images.githubusercontent.com/219043/168146501-3ae61a18-262b-4628-880c-b9470539b142.png)

**Comment by floryst** [comment]
I updated the link, but the displayed link stays lowercase despite it going to the correct URL.
