### ISSUE TITLE
Consider renaming the project from Glance to glance

### ISSUE THREAD

**Issue by jcfr** [Kitware/glance#438]
As outlined in npm naming guidelines [^1]

> all the characters in the package name must be lowercase i.e., no uppercase or mixed case names are allowed

and considering glance is itself published as a npm package [^2], this would ensure consistency.

Also worth noting that other Kitware application informally follow this convention:

```
https://github.com/Kitware/vtk-js
https://github.com/Kitware/dive
https://github.com/Kitware/trame
https://github.com/Kitware/itk-vtk-viewer
https://github.com/Kitware/girder
...
```

[^1]: https://github.com/npm/validate-npm-package-name#naming-rules
[^2]: https://www.npmjs.com/package/paraview-glance

**Comment by jcfr** [comment]
The current problem is that the name glance is already used by another project on npm, see https://www.npmjs.com/package/glance

**Comment by floryst** [comment]
The package name being taken is fine. If we need to publish this (which I think shouldn't make sense for glance), we can use `@kitware/glance`.

**Comment by floryst** [comment]
I can agree to renaming the repo to `glance` for consistency. I also noted that the sidebar link stays lowercase, despite me putting an uppercase letter in it.

**Comment by aylward** [comment]
Actually - the logo will use Glance - not glance - for Consistency with ParaView etc.  This is an application, not a library.
