### ISSUE TITLE
How to add a progress bar with %age while loading data?

### ISSUE THREAD

**Issue by rajat-panwar1** [Kitware/glance#441]

**Comment by rajat-panwar1** [comment]
assuming the data is being uploaded from only from s3 bucket.

**Comment by floryst** [comment]
If you are looking for a progress bar that shows when downloading your dataset into Glance, then check out https://github.com/Kitware/glance/pull/442. Once that is merged, then that will report download progress.

**Comment by rajat-panwar1** [comment]
yeah, that is what i am looking for, thanks for the update but when do think that process will be done by?
