### ISSUE TITLE
Annotations and painting error

### ISSUE THREAD

**Issue by oogetyboogety** [Kitware/glance#446]
When trying to reproduce the example in https://vimeo.com/366511524 using https://kitware.github.io/glance/app/, I get the following error:
ParaViewGlance: master
Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

```
Uncaught TypeError: Cannot read properties of undefined (reading 'search')
```

**Comment by floryst** [comment]
That looks to be an issue that has been resolved with the latest vtk.js version. I will update accordingly.
