### ISSUE TITLE
Bug: actor not centered and orientation widget disappearing after switching from Quad View

### ISSUE THREAD

**Issue by Julesdevops** [Kitware/glance#450]
As it can be seen on the attached gif, odd things happens after going from Quad View to single 3d view.
- The view is zoomed in
- The camera no longer focuses the actor center
- The orientation widget is no longer visible

Also worth mentioning that in a previous version of glance (https://github.com/Kitware/glance/commit/a3163da5a6d5d435bfd89a0196194fa9e946932d), the orientation widget does not disappear but instead gets bigger (kind of permanently zoomed in).

Thanks in advance for your help!

![bug-glance-1-github](https://user-images.githubusercontent.com/58701261/184935676-f94b7d2b-eb34-4918-9f70-740b853d53b8.gif)

**Comment by floryst** [comment]
#451 will address the orientation issue, but I can't seem to repro the zoomed-in view / camera center issue, even after following the steps above. Once #451 is merged, can you test this behavior again?

**Comment by Julesdevops** [comment]
Yes, will do for sure. Thanks for the feedback

**Comment by Julesdevops** [comment]
@floryst I'm observing the same behavior with the latest version. (and the widget still disappears)
I noticed that the camera center/zoom in issue fixes itself when resizing the browser window (opening/closing developer tools for instance)

**Comment by floryst** [comment]
Is it any dataset? is reproducible across different browsers?

I have a fix out for the orientation widget disappearing, but not the center-focus issue.

**Comment by Julesdevops** [comment]
I'm using this dataset from girder: coronacases_org_002_crop.nii.gz 
You're right, I do not observe the camera/center issue with google chrome (Version 105.0.5195.125 (Official Build) (64-bit))
Only with firefox (105.0.1)

**Comment by Julesdevops** [comment]
@floryst some good news, I'm not observing this problem anymore on firefox 106.0.0 but I don't know why (did not find anything relevant in firefox release notes for 105.0.2 and 105.0.3)

**Comment by floryst** [comment]
Huh, well glad that's fixed. It's really weird that the issue was associated with a firefox version. I'll close this as resolved, unless it comes up again.
