### ISSUE TITLE
Bug: Cropping of vtkImageData does not crop the slices

### ISSUE THREAD

**Issue by DavidBerger98** [Kitware/glance#458]
When using a crop on an image data it crops the volume but not the slices (see image below).

![image](https://user-images.githubusercontent.com/24410244/196906708-9ba112ae-d36a-4579-b210-512b7e4fd7ef.png)

**Comment by floryst** [comment]
For cropping, would there be an expectation to also crop the 2D slices? The primary goal is to crop the 3D view, with the 2D views serving as reference. If there is a use-case for 2D cropping, we can add that as a toggle or default functionality.

**Comment by aylward** [comment]
I personally would rather see it operate in the way it is operating...the crop tool overlaid on the 2D, with its impact limited to the 3D view.  It is easier to position it if I can see the data around it in the 2D view.

What is the benefit / use-case for cropping the 2D view versus just zooming-in or such?   In 3D it removes occlusions, but in 2D there are no occlusions, so???

**Comment by DavidBerger98** [comment]
Yes, that makes sense to me. My bad, I didn't think this was intended behavior.

Closing this.
