### ISSUE TITLE
Bug: restore state with Label Maps

### ISSUE THREAD

**Issue by Julesdevops** [Kitware/glance#459]
## Description
Unable to load state from file, with state generated with a remote dataset after using the PaintWidget on it.

## Reproduce
- Load a remote dataset (from girder for instance) into glance
- create a label map and use the paintwidget
- hit 'Save State'
- hit f5 to reload Glance
- load the state file generated at step 3

The dataset does not show up and there is an error in the console.
If you save the state with a local dataset, there is no error, everything is working as intended

## expected behavior
One should be able to restore the state successfully

**Comment by floryst** [comment]
Please look over #460. That should fix your issue.

**Comment by Julesdevops** [comment]
Yes seems like it fixes it, thanks a lot
