### ISSUE TITLE
Errors with shading when opening Lysozome example

### ISSUE THREAD

**Issue by TomTranter** [Kitware/glance#467]
Hi,

I'm just discovering glance. First off - thanks for providing this tool it looks excellent. I'm just experiencing some errors though when running the example online at https://kitware.github.io/glance/app/ and also when I compile it locally

ParaViewGlance: master
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

```
Error linking shader Varying `vertexIDVSOutput` has static-use in the frag shader, but is undeclared in the vert shader.
Links failed: 
TypeError: cellBO.getProgram() is null
TypeError: cellBO.getProgram() is null
TypeError: cellBO.getProgram() is null
```

**Comment by floryst** [comment]
This should be resolved now.
