### ISSUE TITLE
Whether types under the representation module support 3D Glyphs

### ISSUE THREAD

**Issue by haoxl3** [Kitware/glance#481]
When I open vtk with paraview desktop, I can set the type to 3D glyphs. 
<img width="765" alt="image" src="https://github.com/Kitware/glance/assets/15046133/bc1b6c65-6e48-4570-8edd-c4e6a8bf446e">

I find that there are only these Settings on glance.
<img width="376" alt="image" src="https://github.com/Kitware/glance/assets/15046133/2f3e1f79-c84f-4256-b731-dbe8e4364f40">

Do you support 3D glyphs or how do I achieve this function?

**Comment by floryst** [comment]
We currently do not support rendering data arrays as 3D glyphs. I do not have any availability to add it at this time, so if you'd like to contribute it I can point you in the right direction.
