### ISSUE TITLE
Question about Unresolved variable aboutDialog in the project

### ISSUE THREAD

**Issue by bodenstandig** [Kitware/glance#496]
Hi there, I am a undergraduate student majoring in computer engineering and I am using this project to do my final project. Thanks a lot for your contribution to the community! 

Due to my lack of knowledge on vue, it really confused me that I cannot find out the relation between "AboutDialog" and "aboutBox", as shown in the figure, no usages in all places in all files, though they must have strong connections, since when I modify the template in aboutBox, the result will show clearly on the website.
![image](https://github.com/Kitware/glance/assets/106466517/1c1d9d81-b1e2-4319-927c-664d807aa753)
![image](https://github.com/Kitware/glance/assets/106466517/ea8c4939-4806-4fda-8941-6f38911aa000)
(Path: src/components/core/App)

![image](https://github.com/Kitware/glance/assets/106466517/e62efcd1-5d12-4eee-ac9d-61031dca0276)
I am also wondering about the description here, "v-model="aboutDialog"". Since nowhere gives clear definition of aboutDialog in the whole project.  

I have been trapped in this problem for about a week and I cannot add any new functions on the app unless I figure out the project structure.

So, Thanks a lot if someone can help me solving this question!

**Comment by floryst** [comment]
Hi there! The `v-model="..."` syntax is [part of vue](https://vuejs.org/guide/components/v-model.html). It is syntactic sugar for constructing a two-way binding between the variable `aboutDialog` and the component state. `aboutDialog` is just a boolean flag that indicates whether to show the dialog box (true=yes, false=no).

Generally, methods and data properties available on the component (the js component files) are available for use in the template (the html files).

**Comment by bodenstandig** [comment]
Hi there ! I solved the problem following your guidance and thanks very much for your kindly and patient reply!
