### ISSUE TITLE
3D view and slice view navigation point function code implementation, slice intersection point navigation. How to implement it? Do you have any experts to guide you

### ISSUE THREAD

**Issue by linhuanfeng** [Kitware/glance#505]
3D view and slice view navigation point function code implementation, slice intersection point navigation. How to implement it? Do you have any experts to guide you

**Comment by floryst** [comment]
Are you referring to crosshairs functionality? The basic idea of crosshairs for IJK image slicing is, given a 3D world point, convert that point into image space and use those values as the IJK slicing values. Glance currently doesn't have such functionality, but it can be added.
